### ISSUE TITLE
Document creating screenshot from Markdown in the Readme

### ISSUE THREAD

**Issue by frankgerhardt** [concordion/concordion-screenshot-extension#5]
Here https://github.com/concordion/concordion-screenshot-extension#explicitly-adding-screenshots-to-the-output the HTML syntax is described. 

```html
<html xmlns:concordion="http://www.concordion.org/2007/concordion"
      xmlns:ext="urn:concordion-extensions:2010">

....
<div ext:screenshot=""/>
...
```

But how to do this in Markdown where you can't just add another div?

I tried something like `[explicit screenshot](- "ext:screenshot=''")` and `(- 'ext:screenshot=""')`. This seems close but it does not work. I get `java.lang.RuntimeException: Invalid expression [ext:screenshot]`.

**Comment by nigelcharman** [comment]
Added. Let me know if you have any problems with this?

**Comment by frankgerhardt** [comment]
Thanks! It works. The Kotlin syntax is

```kotlin
@ConcordionOptions(declareNamespaces=arrayOf("ext", "urn:concordion-extensions:2010"))
```
